name: build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  coverage:
    name: Check whether we can build every site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Racket
        uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: 'x64'  # or: 'x64', 'x86', 'arm32', 'arm64'
          distribution: 'full' # or: 'minimal'
          variant: 'CS'        # or: 'BC' for Racket Before Chez
          version: '8.7'

      - name: Install package
        run: raco pkg install --auto --no-docs -n racket-lang-org `pwd`

      - name: Build everything (headless display via xvfb)
        run: xvfb-run racket -l- racket-lang-org/sync --save-temps --render-locally Web
